In [2]:
import numpy as np

def check_symmetric(matrix):
    n = len(matrix)
    for i in range(n):
        for j in range(i):
            if matrix[i][j] != matrix[j][i]:
                print(f"非対称です。matrix[{i}][{j}] = {matrix[i][j]}, matrix[{j}][{i}] = {matrix[j][i]}")
                return False, (i, j), (matrix[i][j], matrix[j][i])
    return True, None, None


adjacency_matrix = np.array([
    [0, 10, 55, 20, 0, 0, 0, 0],
    [10, 0, 0, 0, 20, 40, 0, 0],
    [55, 0, 0, 0, 0, 10, 15, 0],
    [20, 0, 0, 0, 20, 0, 55, 0],
    [0, 20, 0, 20, 0, 10, 0, 0],
    [0, 40, 10, 0, 10, 0, 30, 50],
    [0, 0, 15, 55, 0, 30, 0, 20],
    [0, 0, 0, 0, 0, 50, 20, 0]
])

check_symmetric(adjacency_matrix)
print(adjacency_matrix)

def dijkstra(graph, start_node):
    num_vertices = len(graph)
    distances = {node: float('inf') for node in range(num_vertices)}
    distances[start_node] = 0
    unvisited_nodes = set(range(num_vertices))
    previous_nodes = {node: None for node in range(num_vertices)}

    while unvisited_nodes:
        current_node = min(unvisited_nodes, key=lambda node: distances[node])
        unvisited_nodes.remove(current_node)

        for neighbor in range(num_vertices):
            if graph[current_node][neighbor] > 0:
                new_distance = distances[current_node] + graph[current_node][neighbor]
                if new_distance < distances[neighbor]:
                    distances[neighbor] = new_distance
                    previous_nodes[neighbor] = current_node
    return distances, previous_nodes

def get_shortest_path(previous_nodes, start_node, target_node):
    path = []
    current_node = target_node
    while current_node is not None:
        path.insert(0, current_node)
        current_node = previous_nodes[current_node]
    if path[0] != start_node:
        return None
    return path

start_node = 0
target_node = 7
distances, previous_nodes = dijkstra(adjacency_matrix, start_node)
shortest_path = get_shortest_path(previous_nodes, start_node, target_node)

if shortest_path:
    print(f"v{start_node+1}からv{target_node+1}までの最短経路: {[f'v{node+1}' for node in shortest_path]}")
    print(f"距離: {distances[target_node]}")
else:
    print(f"v{start_node+1}からv{target_node+1}への経路が見つかりませんでした。")


[[ 0 10 55 20  0  0  0  0]
 [10  0  0  0 20 40  0  0]
 [55  0  0  0  0 10 15  0]
 [20  0  0  0 20  0 55  0]
 [ 0 20  0 20  0 10  0  0]
 [ 0 40 10  0 10  0 30 50]
 [ 0  0 15 55  0 30  0 20]
 [ 0  0  0  0  0 50 20  0]]
v1からv8までの最短経路: ['v1', 'v2', 'v5', 'v6', 'v3', 'v7', 'v8']
距離: 85
